# Aceita conexões de fora do container
bind 0.0.0.0

# Senha obrigatória (altere via arquivo antes de subir em produção)
requirepass q52ma/BY7Z+4mJAucRLoQ/HiwbC3g3QGMOM1aj+twAqjZrPRhet2C6AguHtEVKvgnAIuqedC1kinDsaW

# Persistência
appendonly yes
save 900 1
save 300 10
save 60 10000