echo "PORTAINER_CONSOLE_PWD=$(openssl rand -base64 36 | tr -d '\n')" >>credentials.conf
echo "MYSQL_ROOT_PWD_FSW=$(openssl rand -base64 36 | tr -d '\n')" >>credentials.conf
echo "MYSQL_USER_PWD_FSW=$(openssl rand -base64 36 | tr -d '\n')" >> credentials.conf
echo "POSTGRES_PWD_FSW=$(openssl rand -base64 36 | tr -d '\n')" >> credentials.conf
echo "PGADMIN_DEFAULT_PWD_ADMIN=$(openssl rand -base64 36 | tr -d '\n')" >> credentials.conf
echo "KEYCLOAK_BD_PWD_FSW=$(openssl rand -base64 36 | tr -d '\n')" >> credentials.conf
echo "KEYCLOAK_ADMIN_PWD_FSW=$(openssl rand -base64 36 | tr -d '\n')" >> credentials.conf
echo "REDIS_PWD_FSW=$(openssl rand -base64 36 | tr -d '\n')" >> credentials.conf
