echo "POSTGRES_ADMIN_PWD=$(openssl rand -base64 60 | tr -d '\n')" >> .env.dev
echo "PGADMIN_ADMIN_PWD=$(openssl rand -base64 60 | tr -d '\n')" >> .env.dev
echo "POSTGRES_PRAXIS_USER_PWD=$(openssl rand -base64 32 | tr -d '\n')" >> .env.dev
echo "PGADMIN_PRAXIS_USER_PWD=$(openssl rand -base64 32 | tr -d '\n')" >> .env.dev
echo "REDIS_ADMIN_PWD=$(openssl rand -base64 60 | tr -d '\n')" >> .env.dev
echo "REDIS_PRAXIS_USER_PWD=$(openssl rand -base64 32 | tr -d '\n')" >> .env.dev
