spring.application.name=praxis-monolito

#datasource connection
# spring.datasource.url=jdbc:postgresql://www.praxis.local:5432/praxis_db_dev
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.datasource.username=postgres
#spring.datasource.password=Admin123

#spring.jpa.properties.hibernate.format_sql=false

# hikari connection pool
#spring.datasource.hikari.maximum-pool-size=5
#spring.datasource.hikari.minimum-idle=3
#spring.datasource.hikari.idle-timeout=10000

# flyway locations for baseline migration scripts and callback lifecycle scripts  
#spring.flyway.locations=classpath:db/setupschema,classpath:db/migration,classpath:db/testdata

# show sql
#spring.jpa.show-sql=true

# # Allows Hibernate to generate SQL optimized for a particular DBMS
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect
