spring.config.activate.on-profile=dev

#datasource connection
# spring.datasource.url=jdbc:postgresql://praxis.local:5432/praxis_db_dev
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.datasource.username=postgres
#spring.datasource.password=Admin123

#spring.jpa.properties.hibernate.format_sql=false

# hikari connection pool
#spring.datasource.hikari.maximum-pool-size=5
#spring.datasource.hikari.minimum-idle=3
#spring.datasource.hikari.idle-timeout=10000

# flyway locations for baseline migration scripts and callback lifecycle scripts  
#spring.flyway.locations=classpath:db/setupschema,classpath:db/migration,classpath:db/legacydata

# show sql
#spring.jpa.show-sql=true

# # Allows Hibernate to generate SQL optimized for a particular DBMS
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect

# CONFIGURA��O DO OAUTH2 CLIENT (Para o Template Engine / Login Web)
spring.security.oauth2.client.registration.keycloak.client-id: web-template-client
spring.security.oauth2.client.registration.keycloak.client-secret: SEU_CLIENT_SECRET_AQUI
spring.security.oauth2.client.registration.keycloak.scope: openid, profile, email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type: authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
spring.security.oauth2.client.provider.keycloak.issuer-uri: http://localhost:8080/realms/dev
spring.security.oauth2.client.provider.keycloak.user-name-attribute: preferred_username

# CONFIGURA��O DO RESOURCE SERVER (Para proteger a API REST com Bearer Token)
spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:8080/realms/dev
