spring.config.activate.on-profile=staging

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Enable Spring Cloud Vault
spring.cloud.vault.enabled=true
spring.config.import=vault://


# Vault Connection Settings
spring.cloud.vault.uri=http://localhost:8200
spring.cloud.vault.connection-timeout=5000
spring.cloud.vault.read-timeout=15000


# Authentication - Token based ( for dev )
spring.cloud.vault.authentication=TOKEN
spring.cloud.vault.token=myroot

# key-value v2 backend ( vault's default)
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret
spring.cloud.vault.kv.default-context=${spring.application.name}

# fail fast if Vault in not available
spring.cloud.vault.fail-fast=true

# SSL Configuration ( disable for local dev )
spring.cloud.vault.ssl.trust-store-type=JKS



