# Flyway: for repair in migrations by Maven
# build -> ./mvnw flyway:repair -Dflyway.configFiles=src/main/resources/flyway.properties
flyway.url=jdbc:postgresql://www.praxis.local:5432/praxis_db_dev
flyway.username=postgres
flyway.password=Admin123