services:
    postgresql-sgbd-fabrica:
        image: postgres:17-alpine
        container_name: postgresql-fsw
        # Resource Limits Block
        deploy:
           resources:
              limits:
               cpus: '1.0'      # Cap database at max 1 full CPU core
               memory: 1024MB    # Hard limit on RAM allocation
              reservations:
               cpus: '0.25'     # Guaranteed minimum CPU fraction
               memory: 256MB     # Guaranteed minimum RAM block
        env_file:
            - .env   
        environment:
            POSTGRES_USER: ${POSTGRES_USER_FSW}
            POSTGRES_PASSWORD: ${POSTGRES_PWD_FSW}
            POSTGRES_DB: ${POSTGRES_DB_FSW}
        volumes:
            - postgres_data_fsw:/var/lib/postgresql
        ports:
            - "${POSTGRES_HOST_FSW}:${POSTGRES_CONTAINER_FSW}"
        networks:
            - praxis-network
        restart: unless-stopped
        
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 3
            
  # postgresql-sgbd-homolog:
  #     container_name: postgresql-hml
  
    pgadmin-console:
        image: dpage/pgadmin4:latest
        container_name: pgadmin-cli
        deploy:
            resources:
              limits:
                cpus: '0.5'
                memory: 512MB
              reservations:
                cpus: '0.2'
                memory: 256MB
        env_file:
            - .env
        environment:
            # explicitly tell pgAdmin to permit internal or local top-level domains
            # PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS: ${PGADMIN_EMAIL_DOMAINS} 
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL_FSW}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PWD_FSW}
            PGADMIN_LISTEN_ADDRESS: ${PGADMIN_LISTEN_ADDRESS}    
            PGADMIN_CONFIG_CHECK_EMAIL_DELIVERABILITY: ${PGADMIN_CONFIG_CHECK_EMAIL}
            TZ: ${PGADMIN_TZ}
            # For enables or disables the pgadmin4 login screen.
            PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE}
            # Deixa explícito a porta em que o pgAdmin escuta dentro do contêiner.
            PGADMIN_LISTEN_PORT: ${PGADMIN_CONTAINER}
        volumes:
            - pgadmin_data_client:/var/lib/pgadmin 
        ports:
            - "${PGADMIN_HOST}:${PGADMIN_CONTAINER}"
        networks:
            - praxis-network
        restart: unless-stopped
        depends_on:
            postgresql-sgbd-fabrica:
              condition: service_healthy

volumes:
    postgres_data_fsw:
    pgadmin_data_client:

networks:
    praxis-network:
        name: praxis-network
        driver: bridge

