services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.4
    container_name: keycloak
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1500MB
        reservations:
          cpus: '0.5'
          memory: 1000MB
    command: ["start-dev", "--proxy-headers=xforwarded"]
#    command: start-dev --hostname-strict=false --hostname-strict-https=false --proxy-headers=xforwarded
    env_file: 
      - .env
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_LOGIN_FSW}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PWD_FSW}
      KC_DB: ${KEYCLOAK_BD_SGBD_FSW}
      #      KC_DB_URL: jdbc:mysql://${KC_DB_URL_HOST}:${KC_DB_URL_PORT}/${MYSQL_DATABASE}?useSSL=false&characterEncoding=UTF-8
      KC_DB_URL: ${KEYCLOAK_BD_URL_FSW}
      KC_DB_USERNAME: ${MYSQL_USER_FSW}
      KC_DB_PASSWORD: ${MYSQL_USER_PWD_FSW}
      # Define que o Keycloak está atrás de um proxy reverso (como Nginx, HAProxy, AWS ALB, Traefik).
      KC_PROXY: edge
      # Informa ao Keycloak para ler e confiar nos cabeçalhos padrão X-Forwarded-* (como X-Forwarded-For, X-Forwarded-Proto, X-Forwarded-Host) enviados pelo seu proxy para identificar o IP real e o protocolo do cliente.
      KC_PROXY_HEADERS: "xforwarded"
      # Desliga exigência de domínio único para testes    
      KC_HOSTNAME_STRICT: "false"
      # Permite que o Keycloak aceite URLs de redirecionamento e endpoints usando o protocolo HTTP (sem criptografia).Atenção: Use apenas em ambientes de desenvolvimento. Em produção, mantenha como true.
      KC_HOSTNAME_STRICT_HTTPS: "false"
      # Permite que as URLs de comunicação interna (backchannel), como as usadas por adaptadores ou microsserviços para validar tokens, sejam resolvidas dinamicamente com base na requisição atual, em vez de usar uma URL fixa.
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: "true"
      KC_HTTP_ENABLED: "true" # Permite http internamente no docker
      #KC_HOSTNAME: "https://recoup-slip-strained.ngrok-free.dev"
      KC_HOSTNAME: "http://keycloak.suasflux.prem"
      #KC_HOSTNAME: "http://keycloak.tech"
      #KC_HOSTNAME: "http://localhost"
      
      
    ports:
      - "${KEYCLOAK_HOST_FSW}:${KEYCLOAK_CONTAINER_FSW}"
    networks:
      - suasflux-network
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
# keycloak-iam-homolog:
#   image: quay.io/keycloak/keycloak:26.6.4
#   container_name: keycloak-hml

networks:
    suasflux-network:
        name: suasflux-network
        driver: bridge
