services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer-infra
    env_file:
      - .env 
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data_infra:/data
    ports:
      - "${PORTAINER_HTTP_HOST}:${PORTAINER_HTTP_CONTAINER}"
      #- 8000:8000  # Remove if you do not intend to use Edge Agents
    networks:
     - praxis-network
     
volumes:
  portainer_data_infra:
    name: portainer_data_infra

 
networks:
  praxis-network:
    name: praxis-network
    driver: bridge