services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-manager
    deploy:
      resources:
        reservations:
          cpus: '0.10' # Garante pelo menos 10% de 1 núcleo
          memory: 150MB # Garante pelo menos 150MB de RAM
        limits:
          cpus: '0.50' # Não deixa passar de 50% de 1 núcleo
          memory: 350MB # Não deixa passar de 350MB de RAM 
    env_file: 
      - .env
    restart: unless-stopped
    ports:
      - "${NGINX_HTTP_HOST}:${NGINX_HTTP_CONTAINER}" # Public HTTP Port
      - "${NGINX_HTTPS_HOST}:${NGINX_HTTPS_CONTAINER}" # Public HTTPS Port
      - "${NGINX_WEBADMIN_HOST}:${NGINX_WEBADMIN_CONTAINER}" # Admin Web Port
      # Add any other Stream port you want to expose
      # - "21:21" # FTP
      # - "${MYSQL_HOST_FSW}:${MYSQL_CONTAINER_FSW}" # MySQL FSW
      # - "${POSTGRES_HOST_FSW}:${POSTGRES_CONTAINER_FSW}" # PostgreSQL FSW
      # - "${REDIS_HOST_FSW}:${REDIS_CONTAINER_FSW}" # Redis FSW
    environment:
      TZ: "America/Recife"
      
    volumes: 
      - nginx_proxy_data:/data # Armazena as configurações dos seus proxies  
      - nginx_ssl_data:/etc/letsencrypt # Armazena os certificados SSL 
    networks:
      - suasflux-network
      
    healthcheck: 
      test: ["CMD", "/usr/bin/check-health"] 
      interval: 10s 
      timeout: 3s 
      retries: 3 
      start_period: 10s

networks:
  suasflux-network:
    name: suasflux-network
    driver: bridge
    
volumes:
    nginx_proxy_data:
    nginx_ssl_data:
    # Armazena as configurações dos seus proxies
    # - ./data:/data
    # Armazena os certificados SSL
    # - ./letsencrypt:/etc/letsencrypt

