services:
  portainer-infra:
    image: portainer/portainer-ce:lts
    container_name: portainer-hub
    deploy:
      resources:
        limits:
          cpus: '0.50'     # Cap usage at 50% of a single CPU core
          memory: 512M     # Hard cap on RAM usage
        reservations:
          cpus: '0.25'     # Guarantee 25% of a core is available
          memory: 256M     # Guarantee 256MB of RAM is available
    env_file:
      - .env 
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data_infra:/data
    ports:
      - "${PORTAINER_HTTP_HOST}:${PORTAINER_HTTP_CONTAINER}"
      #- 8000:8000  # Remove if you do not intend to use Edge Agents
    networks:
     - praxis-network
     
volumes:
  portainer_data_infra:
    name: portainer_data_infra

 
networks:
  praxis-network:
    name: praxis-network
    driver: bridge