services:
    postgres-fsw:
        image: postgres:17-alpine
        container_name: postgres-fsw
        env_file:
            - .env   
        environment:
            POSTGRES_USER: ${KEY_POSTGRES_USER_FSW}
            POSTGRES_PASSWORD: ${KEY_POSTGRES_PASSWORD_FSW}
            POSTGRES_DB: ${KEY_POSTGRES_DB_FSW}
        volumes:
            - postgres_data_fsw:/var/lib/postgresql
        ports:
            - "${POSTGRES_HOST_FSW}:${POSTGRES_CONTAINER_FSW}"
        networks:
            - praxis-network
        restart: unless-stopped
        
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 3

    pgadmin-client:
        image: dpage/pgadmin4:latest
        container_name: pgadmin-client
        env_file:
            - .env
        environment:
            # explicitly tell pgAdmin to permit internal or local top-level domains
            # PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS: ${KEY_PGADMIN_EMAIL_DOMAINS} 
            PGADMIN_DEFAULT_EMAIL: ${KEY_PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${KEY_PGADMIN_DEFAULT_PASSWORD}
            PGADMIN_LISTEN_ADDRESS: ${KEY_PGADMIN_LISTEN_ADDRESS}    
            PGADMIN_CONFIG_CHECK_EMAIL_DELIVERABILITY: ${KEY_PGADMIN_CONFIG_CHECK_EMAIL}
            TZ: ${KEY_TZ}
            # For enables or disables the pgadmin4 login screen.
            PGADMIN_CONFIG_SERVER_MODE: ${KEY_PGADMIN_CONFIG_SERVER_MODE}
            # Deixa explícito a porta em que o pgAdmin escuta dentro do contêiner.
            PGADMIN_LISTEN_PORT: ${PGADMIN_CONTAINER}
        volumes:
            - pgadmin_data_client:/var/lib/pgadmin 
        ports:
            - "${PGADMIN_HOST}:${PGADMIN_CONTAINER}"
        networks:
            - praxis-network
        restart: unless-stopped
        depends_on:
            postgres-fsw:
              condition: service_healthy

volumes:
    postgres_data_fsw:
    pgadmin_data_client:

networks:
    praxis-network:
        name: praxis-network
        driver: bridge

