# networks:
#    suasflux-hub:
#        driver: bridge
#    suasflux-prem:
#        driver: bridge

networks:
    suasflux-network:
        driver: bridge

volumes:
    mariadb_data:
    mysql_data:
    minio_data:
    nginx_proxy_data:
    nginx_ssl_data:
    postgres_data:
    pgadmin_data:
    rabbitmq_data:
    redis_data:
    redisinsight_data:   
    portainer_data:
