services:
  redis-cache:
    image: redis:8.2
    container_name: redis-fsw
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD_FSW}
#   command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "${REDIS_HOST_FSW}:${REDIS_CONTAINER_FSW}"
    
    volumes:
#     - ../redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis_data_fsw:/data
    networks:
      - praxis-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  redisinsight-client:
    image: redis/redisinsight:latest
    container_name: redisinsight-client
    restart: unless-stopped
    ports:
      - "${REDISINSIGHT_HOST_FSW}:${REDISINSIGHT_CONTAINER_FSW}"
    depends_on:
      redis-fsw:
        condition: service_healthy
    volumes:
      - redisinsight_data_client:/data
    networks:
      - praxis-network
#    environment:
#      - RI_APP_FEATURES=browser,database_analysis,workbench
#      - REDISINSIGHT_CONNECTIONS=[{"name":"Local Redis","host":"redis","port":6379,"username":"","password":"q52ma/BY7Z+4mJAucRLoQ/HiwbC3g3QGMOM1aj+twAqjZrPRhet2C6AguHtEVKvgnAIuqedC1kinDsaW"}]
      
networks:
  praxis-network:
    name: praxis-network

volumes:
  redis_data_fsw:
  redisinsight_data_client:
