services:
    postgres:
        image: postgres:latest
        container_name: postgres-dev
        env_file:
            - .env   
        environment:
            POSTGRES_USER: ${KEY_POSTGRES_USER}
            POSTGRES_PASSWORD: ${KEY_POSTGRES_PASSWORD}
            POSTGRES_DB: ${KEY_POSTGRES_DB}
        volumes:
            - postgres_data_dev:/var/lib/postgresql
        ports:
            - "${POSTGRES_HOST}:${POSTGRES_CONTAINER}"
        networks:
            - praxis-network
        restart: unless-stopped

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin-dev
        env_file:
            - .env
        environment:
            # explicitly tell pgAdmin to permit internal or local top-level domains
            # PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS: ${KEY_PGADMIN_EMAIL_DOMAINS} 
            PGADMIN_DEFAULT_EMAIL: ${KEY_PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${KEY_PGADMIN_DEFAULT_PASSWORD}
            PGADMIN_LISTEN_ADDRESS: ${KEY_PGADMIN_LISTEN_ADDRESS}    
            PGADMIN_CONFIG_CHECK_EMAIL_DELIVERABILITY: ${KEY_PGADMIN_CONFIG_CHECK_EMAIL}
            TZ: ${KEY_TZ}
            # For enables or disables the pgadmin4 login screen.
            PGADMIN_CONFIG_SERVER_MODE: ${KEY_PGADMIN_CONFIG_SERVER_MODE}
            # Deixa explícito a porta em que o pgAdmin escuta dentro do contêiner.
            PGADMIN_LISTEN_PORT: ${PGADMIN_CONTAINER}
        volumes:
            - pgadmin_data_dev:/var/lib/pgadmin
        depends_on:
            - postgres
        ports:
            - "${PGADMIN_HOST}:${PGADMIN_CONTAINER}"
        networks:
            - praxis-network
        restart: unless-stopped

volumes:
    postgres_data_dev:
    pgadmin_data_dev:

networks:
    praxis-network:
        name: praxis-network
        driver: bridge

