services:
  keycloak-iam-fabrica:
    image: quay.io/keycloak/keycloak:26.6.3
    container_name: keycloak-fsw
    command: start-dev
    env_file: 
      - .env
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_LOGIN_FSW}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PWD_FSW}
       # Configuração do Banco de Dados vinculada ao serviço acima
      KC_DB: ${KEYCLOAK_BD_SGBD_FSW}
      KC_DB_URL: ${KEYCLOAK_BD_URL_FSW}
      KC_DB_USERNAME: ${KEYCLOAK_BD_USER_FSW}
      KC_DB_PASSWORD: ${KEYCLOAK_BD_PWD_FSW}
    ports:
      - "${KEYCLOAK_HOST_FSW}:${KEYCLOAK_CONTAINER_FSW}"
    depends_on:
      mysql-sgbd-fabrica:
        condition: service_healthy
# keycloak-iam-homolog:
#   image: quay.io/keycloak/keycloak:26.6.3
#   container_name: keycloak-hml

networks:
    praxis-network:
        name: praxis-network
        driver: bridge
