services:
  mysql-sgbd-fabrica:
    image: mysql:9.7
    container_name: mysql-fsw
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1GB
        reservations:
          cpus: '0.5'
          memory: 512MB
    env_file:
        - .env   
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PWD_FSW}
        MYSQL_DATABASE: ${MYSQL_DB_FSW}
        MYSQL_USER: ${MYSQL_USER_FSW}
        MYSQL_PASSWORD: ${MYSQL_USER_PWD_FSW}
    volumes:
        - mysql_data_fsw:/var/lib/mysql
        # Optional: Uncomment below to automatically run initial SQL scripts on startup
      # - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
        - "${MYSQL_HOST_FSW}:${MYSQL_CONTAINER_FSW}"
    networks:
        - praxis-network
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PWD_FSW}"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 30s  # Dá 30 segundos livres para o banco ligar
      
 # mysql-sgbd-homolog:
 #   container_name: mysql-hml
 
  phpmyadmin-console:
    image: phpmyadmin:latest
    container_name: phpmyadmin-cli
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512MB
        reservations:
          cpus: '0.25'
          memory: 256MB
    networks:
      - praxis-network
    restart: unless-stopped
    ports:
      - "${PHPMYADMIN_HOST}:${PHPMYADMIN_CONTAINER}"
    env_file:
      - .env 
    environment:
      PMA_HOST_FSW: mysql-fsw
      PMA_PORT_FSW: ${MYSQL_CONTAINER_FSW}
#     PMA_HOST_HOMOLOG: db
#     PMA_PORT_HOMOLOG: 
    depends_on:
      mysql-sgbd-fabrica:
        condition: service_healthy
volumes:
    mysql_data_fsw:

networks:
    praxis-network:
        name: praxis-network
        driver: bridge
                