#include:
#    - path: 
#        - ./docker-compose.nginx.yml
#        - ./docker-compose.portainer.yml
#        - ./docker-compose.postgres.yml 
#      project_directory: ..
#      env_file:
#        - ./infra/.env   
#        - ./dev/.env 
#     - ./app2-data/.env
#
#services:
#    nginx-manager:
#    portainer:
#    postgres:
#    pgadmin:     

networks:
    praxis-network:
        driver: bridge

volumes:
    mysql_data_fsw:
    nginx_proxy_data_infra:
    nginx_ssl_data_infra:
    postgres_data_fsw:
    pgadmin_data_client:
    redis_data_fsw:
    redisinsight_data_client:   
    portainer_data_infra:
