services:
  nginx-manager:
    image: 'jc21/nginx-proxy-manager:2.15.0'
    container_name: nginx-manager
    env_file:
      - .env
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - "${NGINX_HTTP_PORT_HOST}:${NGINX_HTTP_PORT_CONTAINER}" # Public HTTP Port
      - "${NGINX_HTTPS_PORT_HOST}:${NGINX_HTTPS_PORT_CONTAINER}" # Public HTTPS Port
      - "${NGINX_WEBADMIN_PORT_HOST}:${NGINX_WEBADMIN_PORT_CONTAINER}" # Admin Web Port
      # Add any other Stream port you want to expose
      # - "21:21" # FTP
    
    depends_on:
      - postgres  
    environment:
      TZ: "America/Sao Paulo"
    volumes: 
      - ${NGINX_PROXIES_DATA}:${NGINX_PROXIES_PATH} # Armazena as configurações dos seus proxies  
      - ${NGINX_CERTS_DATA}:${NGINX_CERTS_PATH} # Armazena os certificados SSL 
    networks:
      - praxis-network

networks:
  praxis-network:
    name: praxis-network
    driver: bridge
volumes:
    nginx_proxy_data: {NGINX_PROXIES_DATA}
    nginx_ssl_data: {NGINX_CERTS_DATA}
    # Armazena as configurações dos seus proxies
    # - ./data:/data
    # Armazena os certificados SSL
    # - ./letsencrypt:/etc/letsencrypt

