services:
  nginx-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx
    env_file: 
      - .env
    restart: unless-stopped
    ports:
      - "${NGINX_HTTP_HOST}:${NGINX_HTTP_CONTAINER}" # Public HTTP Port
      - "${NGINX_HTTPS_HOST}:${NGINX_HTTPS_CONTAINER}" # Public HTTPS Port
      - "${NGINX_WEBADMIN_HOST}:${NGINX_WEBADMIN_CONTAINER}" # Admin Web Port
      # Add any other Stream port you want to expose
      # - "21:21" # FTP
    environment:
      TZ: "America/Sao Paulo"
      
    volumes: 
      - nginx_proxy_data:/data # Armazena as configurações dos seus proxies  
      - nginx_ssl_data:/etc/letsencrypt # Armazena os certificados SSL 
    networks:
      - praxis-network

networks:
  praxis-network:
    name: praxis-network
    driver: bridge
    
volumes:
    nginx_proxy_data:
    nginx_ssl_data:
    # Armazena as configurações dos seus proxies
    # - ./data:/data
    # Armazena os certificados SSL
    # - ./letsencrypt:/etc/letsencrypt

