services:
  nginx-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx
    env_file: 
      - devstack.env
    restart: unless-stopped
    ports:
      - "${VAR_NGINX_HTTP_PORT_HOST}:80" # Public HTTP Port
      - "${VAR_NGINX_HTTPS_PORT_HOST}:443"  # Public HTTPS Port
      - "${VAR_NGINX_WEBADMIN_PORT_HOST}:81"  # Admin Web Port
      # Add any other Stream port you want to expose
      # - "21:21" # FTP
    environment:
      TZ: "America/Sao Paulo"
      
    volumes: 
      - nginx_proxy_data:/data # Armazena as configurações dos seus proxies  
      - nginx_ssl_data:/etc/letsencrypt # Armazena os certificados SSL 
    networks:
      - praxis-network

networks:
  praxis-network:
    name: praxis-network
    driver: bridge
    
volumes:
    nginx_proxy_data:
    nginx_ssl_data:
    # Armazena as configurações dos seus proxies
    # - ./data:/data
    # Armazena os certificados SSL
    # - ./letsencrypt:/etc/letsencrypt

