services:
    postgres:
        image: postgres:latest
        container_name: postgres
        env_file: 
            - devstack.env
        environment:
            POSTGRES_USER: ${VAR_POSTGRES_USER}
            POSTGRES_PASSWORD: ${VAR_POSTGRES_PASSWORD}
            POSTGRES_DB: ${VAR_POSTGRES_DB}
        volumes:
            - postgres_data:/var/lib/postgresql/data/pgdata
        ports:
            - "${VAR_POSTGRES_PORT_HOST}:5432"
        networks:
            - praxis-network
        restart: unless-stopped

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin
        env_file: 
            - devstack.env
        environment:
            PGADMIN_DEFAULT_EMAIL: ${VAR_PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${VAR_PGADMIN_DEFAULT_PASSWORD}
            PGADMIN_CONFIG_SERVER_MODE: ${VAR_PGADMIN_CONFIG_SERVER_MODE}
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        depends_on:
            - postgres
        ports:
            - "${VAR_PGADMIN_PORT_HOST}:5050"
        networks:
            - praxis-network
        restart: unless-stopped

networks:
    praxis-network:
        name: praxis-network
        driver: bridge

volumes:
    postgres_data:
    pgadmin_data:
